<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="11" skipped="0" tests="11" time="0.622" timestamp="2022-07-20T15:08:01.581238" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_patient.test_patient" name="test_admin_login_with_default_password" file="FYP\Test\test_patient.py" line="44" time="0.002"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_admin_login_with_default_password&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_database" file="FYP\Test\test_patient.py" line="99" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_database&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_dummy" file="FYP\Test\test_patient.py" line="67" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_dummy&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_existence_of_customer" file="FYP\Test\test_patient.py" line="106" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_existence_of_customer&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_index_login" file="FYP\Test\test_patient.py" line="51" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_index_login&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_login" file="FYP\Test\test_patient.py" line="26" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_login&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_login_v1" file="FYP\Test\test_patient.py" line="33" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_login_v1&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_correct" file="FYP\Test\test_patient.py" line="85" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_pass_correct&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_incorrect" file="FYP\Test\test_patient.py" line="93" time="0.001"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_pass_incorrect&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_test" file="FYP\Test\test_patient.py" line="40" time="0.002"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_test&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_users_login" file="FYP\Test\test_patient.py" line="70" time="0.002"><failure message="NameError: name 'App' is not defined">self = &lt;test_patient.test_patient testMethod=test_users_login&gt;

    def setUp(self):
        # Load test data
&gt;       self.app = App(database='healthcare_db')
E       NameError: name 'App' is not defined

FYP\Test\test_patient.py:105: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>