<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="6" skipped="0" tests="8" time="1.981" timestamp="2022-07-15T15:23:11.134534" hostname="DESKTOP-OREH0UF"><testcase classname="FYP.Test.test_patient.test_patient" name="test_admin_login_with_default_password" file="FYP\Test\test_patient.py" line="40" time="0.050"><failure message="NameError: name 'rq' is not defined">self = &lt;test_patient.test_patient testMethod=test_admin_login_with_default_password&gt;

    def test_admin_login_with_default_password(self):
&gt;       s = rq.Session()
E       NameError: name 'rq' is not defined

FYP\Test\test_patient.py:42: NameError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_dummy" file="FYP\Test\test_patient.py" line="63" time="0.004"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_index_login" file="FYP\Test\test_patient.py" line="47" time="0.011"><failure message="ModuleNotFoundError: No module named 'app'">self = &lt;test_patient.test_patient testMethod=test_index_login&gt;

    def test_index_login(self):
&gt;       with patch("app.session", dict()) as session:

FYP\Test\test_patient.py:49: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1389: in __enter__
    self.target = self.getter()
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1564: in &lt;lambda&gt;
    getter = lambda: _importer(target)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

target = 'app'

    def _importer(target):
        components = target.split('.')
        import_path = components.pop(0)
&gt;       thing = __import__(import_path)
E       ModuleNotFoundError: No module named 'app'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\unittest\mock.py:1236: ModuleNotFoundError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_login" file="FYP\Test\test_patient.py" line="23" time="0.020"><failure message="KeyError: 'logged_in'">self = &lt;test_patient.test_patient testMethod=test_login&gt;

    def test_login(self):
       with app.test_client() as client:
           #client.post('/Patient_Main', data=dict(username='s', password='s'))
           client.get('/Patient_Main', data=dict(username='s', password='s'))
           with client.session_transaction() as sess:
&gt;              self.assertTrue(sess['logged_in'] == True)

FYP\Test\test_patient.py:29: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;SecureCookieSession {}&gt;, key = 'logged_in'

    def __getitem__(self, key: str) -&gt; t.Any:
        self.accessed = True
&gt;       return super().__getitem__(key)
E       KeyError: 'logged_in'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\flask\sessions.py:79: KeyError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_login_v1" file="FYP\Test\test_patient.py" line="30" time="0.010"><failure message="KeyError: 'logged_in'">self = &lt;test_patient.test_patient testMethod=test_login_v1&gt;

    def test_login_v1(self):
       with app.test_client() as client:
           client.post('/LoginController', data=dict(username='wenling', password='password'))
           with client.session_transaction() as session:
&gt;              self.assertTrue(session['logged_in'])

FYP\Test\test_patient.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;SecureCookieSession {}&gt;, key = 'logged_in'

    def __getitem__(self, key: str) -&gt; t.Any:
        self.accessed = True
&gt;       return super().__getitem__(key)
E       KeyError: 'logged_in'

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\site-packages\flask\sessions.py:79: KeyError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_correct" file="FYP\Test\test_patient.py" line="81" time="0.009"><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_pass_incorrect" file="FYP\Test\test_patient.py" line="89" time="0.011"><failure message="AssertionError: False is not true">self = &lt;test_patient.test_patient testMethod=test_pass_incorrect&gt;

    def test_pass_incorrect(self):
        tester = app.test_client(self)
        response = tester.post('/LoginController', data=dict(username = 'wenling', password='password'))
&gt;       self.assertTrue(b'wenling' in response.data)
E       AssertionError: False is not true

FYP\Test\test_patient.py:93: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_patient.test_patient" name="test_users_login" file="FYP\Test\test_patient.py" line="66" time="0.012"><failure message="AssertionError: b'&lt;!doctype html&gt;\n&lt;html lang=en&gt;\n&lt;title[169 chars]p&gt;\n' != 'wenling'">self = &lt;test_patient.test_patient testMethod=test_users_login&gt;

    def test_users_login(self):
        result = self.app.post('/LoginController', data=dict(username='wenling', password='password'), follow_redirects=True)
        #result = self.app.post('/LoginController', data=dict(username='oswaldo', password='password'))
        # I want to check the HTML tag's text value data after logging in
        #self.assertIn(result.data.getTag("h1", b"Nicole") #What I imagined using &lt;h1&gt;
        #self.assertin(result.data.getId("userA", b"Nicole") #What I imagined using id
    
        #This returns true which is okay, because 'Nicole' exists in the whole page
        #self.assertTrue(result, b'wenling')
        #self.assertTrue(result)
&gt;       self.assertEqual(result.data, 'wenling')
E       AssertionError: b'&lt;!doctype html&gt;\n&lt;html lang=en&gt;\n&lt;title[169 chars]p&gt;\n' != 'wenling'

FYP\Test\test_patient.py:77: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>