<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="0" tests="2" time="0.441" timestamp="2022-07-06T18:47:26.617444" hostname="DESKTOP-UCRF95V"><testcase classname="FYP.Test.test_Patient.test_patient" name="test_pass_correct" file="FYP\Test\test_Patient.py" line="29" time="0.016"><failure message="AssertionError: False is not true">self = &lt;test_Patient.test_patient testMethod=test_pass_correct&gt;

    def test_pass_correct(self):
        tester = app.test_client(self)
        response = tester.post('/LoginController', data=dict(username = 'wenling', password='password'))
&gt;       self.assertTrue(b'password' in response.data)
E       AssertionError: False is not true

FYP\Test\test_Patient.py:33: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase><testcase classname="FYP.Test.test_Patient.test_patient" name="test_pass_incorrect" file="FYP\Test\test_Patient.py" line="37" time="0.003"><failure message="AssertionError: False is not true">self = &lt;test_Patient.test_patient testMethod=test_pass_incorrect&gt;

    def test_pass_incorrect(self):
        tester = app.test_client(self)
        response = tester.post('/LoginController', data=dict(username = 'wenling', password='passwor'))
&gt;       self.assertTrue(b'password' in response.data)
E       AssertionError: False is not true

FYP\Test\test_Patient.py:41: AssertionError</failure><system-out>--------------------------------- Captured Log ---------------------------------

--------------------------------- Captured Out ---------------------------------

</system-out><system-err>--------------------------------- Captured Err ---------------------------------

</system-err></testcase></testsuite></testsuites>